export const menu = [
{
    listItems: [
    {
        id: 1,
        title: "HOME",
        url: "/",
        icon: "home.svg",
    },
    {
        id: 2,
        title: "PROJECTS",
        url: "/projects",
        icon: "element.svg",
    },
    {
        id: 3,
        title: "CLIENTS",
        url: "/clients",
        icon: "user.svg",
    },
    {
        id: 4,
        title: "INVOICES",
        url: "/invoices",
        icon: "log.svg",
    },
    ],
},
];

export const clientsData = [
    {
        id: 1,
        image: "/iconmonkey.png",
        name: "JARED HUBERT",
        email: "JAREDH@GMAIL.COM",
        phone: "123 456 789",
        status: "ACTIVE",
        revenue: "£800",
        outstanding: "£300",
        created: "23.12.24",
    },
    {
        id: 2,
        image: "/iconfox.png",
        name: "EMMA JONES",
        email: "EMMAJ@GMAIL.COM",
        phone: "123 456 789",
        status: "ACTIVE",
        revenue: "£600",
        outstanding: "£200",
        created: "10.12.24",
    },
    {
        id: 3,
        image: "/iconlion.png",
        name: "STEVE WORKS",
        email: "STEVEW@GMAIL.COM",
        phone: "123 456 789",
        status: "ACTIVE",
        revenue: "£1,200",
        outstanding: "£400",
        created: "04.12.24",
    },
    {
        id: 4,
        image: "",
        name: "ALICE SMITH",
        email: "ALICES@GMAIL.COM",
        phone: "123 456 789",
        status: "ACTIVE",
        revenue: "£900",
        outstanding: "£0",
        created: "18.11.24",
    },
    {
        id: 5,
        image: "",
        name: "JOHN DOE",
        email: "JOHND@GMAIL.COM",
        phone: "123 456 789",
        status: "ACTIVE",
        revenue: "£1,500",
        outstanding: "£0",
        created: "11.11.24",
    },
    {
        id: 6,
        image: "",
        name: "LUCY GRAY",
        email: "LUCYG@GMAIL.COM",
        phone: "123 456 789",
        status: "ACTIVE",
        revenue: "£750",
        outstanding: "£250",
        created: "06.11.24",
    },
    {
        id: 7,
        image: "",
        name: "MARK ZANE",
        email: "MARKZ@GMAIL.COM",
        phone: "123 456 789",
        status: "ON HOLD",
        revenue: "£500",
        outstanding: "£150",
        created: "21.10.24",
    },
    {
        id: 8,
        image: "",
        name: "NINA COLE",
        email: "NINAC@GMAIL.COM",
        phone: "123 456 789",
        status: "ON HOLD",
        revenue: "£1,000",
        outstanding: "£450",
        created: "10.09.24",
    },
    {
        id: 9,
        image: "",
        name: "PAUL LEE",
        email: "PAULL@GMAIL.COM",
        phone: "123 456 789",
        status: "COMPLETED",
        revenue: "£1,300",
        outstanding: "£0",
        created: "30.08.24",
    },
    {
        id: 10,
        image: "",
        name: "SOPHIE EVANS",
        email: "SOPHIEE@GMAIL.COM",
        phone: "123 456 789",
        status: "COMPLETED",
        revenue: "£1,100",
        outstanding: "£50",
        created: "15.07.24",
    },
    {
        id: 11,
        image: "",
        name: "TOM HARRIS",
        email: "TOMH@GMAIL.COM",
        phone: "123 456 789",
        status: "COMPLETED",
        revenue: "£2,000",
        outstanding: "£0",
        created: "06.06.24",
    },
    {
        id: 12,
        image: "",
        name: "OLIVIA BROWN",
        email: "OLIVIAB@GMAIL.COM",
        phone: "123 456 789",
        status: "COMPLETED",
        revenue: "£850",
        outstanding: "£0",
        created: "25.05.24",
    },
    {
        id: 13,
        image: "",
        name: "DAVID CLARK",
        email: "DAVIDC@GMAIL.COM",
        phone: "123 456 789",
        status: "COMPLETED",
        revenue: "£950",
        outstanding: "£0",
        created: "13.04.24",
    },
];

export const projectsData = [
    {
        id: 1,
        project: "CRYPTO TRACKER",
        status: "ACTIVE",
        client: "JARED HUBERT",
        priority: "LOW",
        budget: "£650",
        tasks: "3/10",
        started: "23.12.24",
        deadline: "28.01.25",
    },
    {
        id: 2,
        project: "ADMIN DASHBOARD",
        status: "ACTIVE",
        client: "EMMA JONES",
        priority: "LOW",
        budget: "£400",
        tasks: "5/11",
        started: "10.12.24",
        deadline: "15.01.25",
    },
    {
        id: 3,
        project: "PORTFOLIO",
        status: "ACTIVE",
        client: "STEVE WORKS",
        priority: "MEDIUM",
        budget: "£700",
        tasks: "3/11",
        started: "04.12.24",
        deadline: "18.01.25",
    },
    {
        id: 4,
        project: "TASK MANAGER",
        status: "ACTIVE",
        client: "ALICE SMITH",
        priority: "HIGH",
        budget: "£900",
        tasks: "9/30",
        started: "18.11.24",
        deadline: "25.01.25",
    },
    {
        id: 5,
        project: "CHAT APP",
        status: "ACTIVE",
        client: "JOHN DOE",
        priority: "LOW",
        budget: "£550",
        tasks: "4/15",
        started: "11.11.24",
        deadline: "10.01.25",
    },
    {
        id: 6,
        project: "LANDING PAGE",
        status: "ACTIVE",
        client: "LUCY GRAY",
        priority: "MEDIUM",
        budget: "£300",
        tasks: "2/10",
        started: "06.11.24",
        deadline: "12.01.25",
    },
    {
        id: 7,
        project: "TRAVEL BOOKING",
        status: "ON HOLD",
        client: "MARK ZANE",
        priority: "LOW",
        budget: "£500",
        tasks: "0/12",
        started: "21.10.24",
        deadline: "N/A",
    },
    {
        id: 8,
        project: "ECOMMERCE STORE",
        status: "ON HOLD",
        client: "NINA COLE",
        priority: "LOW",
        budget: "£850",
        tasks: "6/20",
        started: "10.09.24",
        deadline: "N/A",
    },
    {
        id: 9,
        project: "INVENTORY MANAGER",
        status: "COMPLETED",
        client: "PAUL LEE",
        priority: "N/A",
        budget: "£1000",
        tasks: "16/16",
        started: "30.08.24",
        deadline: "15.09.24",
    },
    {
        id: 10,
        project: "FOOD DELIVERY APP",
        status: "COMPLETED",
        client: "SOPHIE EVANS",
        priority: "N/A",
        budget: "£1200",
        tasks: "20/20",
        started: "15.07.24",
        deadline: "05.08.24",
    },
    {
        id: 11,
        project: "FITNESS TRACKER",
        status: "COMPLETED",
        client: "TOM HARRIS",
        priority: "N/A",
        budget: "£750",
        tasks: "18/18",
        started: "06.06.24",
        deadline: "20.06.24",
    },
    {
        id: 12,
        project: "SOCIAL MEDIA CHAT APP",
        status: "COMPLETED",
        client: "OLIVIA BROWN",
        priority: "N/A",
        budget: "£950",
        tasks: "14/14",
        started: "25.05.24",
        deadline: "10.06.24",
    },
    {
        id: 13,
        project: "WEATHER APP",
        status: "COMPLETED",
        client: "DAVID CLARK",
        priority: "N/A",
        budget: "£500",
        tasks: "12/12",
        started: "13.04.24",
        deadline: "30.04.24",
    },
];

export const invoicesData = [
    {
        id: 1,
        number: "1023",
        project: "CRYPTO TRACKER",
        client: "JARED HUBERT",
        amount: "£800",
        date: "23.12.24",
        method: "BANK TRANSFER",
        status: "UNPAID",
    },
    {
        id: 2,
        number: "1024",
        project: "ADMIN DASHBOARD",
        client: "EMMA JONES",
        amount: "£600",
        date: "10.12.24",
        method: "CREDIT CARD",
        status: "PAID",
    },
    {
        id: 3,
        number: "1025",
        project: "PORTFOLIO",
        client: "STEVE WORKS",
        amount: "£1,200",
        date: "04.12.24",
        method: "BANK TRANSFER",
        status: "PAID",
    },
    {
        id: 4,
        number: "1026",
        project: "TASK MANAGER",
        client: "ALICE SMITH",
        amount: "£900",
        date: "18.11.24",
        method: "PAYPAL",
        status: "OVERDUE",
    },
    {
        id: 5,
        number: "1027",
        project: "CHAT APP",
        client: "JOHN DOE",
        amount: "£1,500",
        date: "11.11.24",
        method: "CREDIT CARD",
        status: "PAID",
    },
    {
        id: 6,
        number: "1028",
        project: "LANDING PAGE",
        client: "LUCY GRAY",
        amount: "£750",
        date: "06.11.24",
        method: "BANK TRANSFER",
        status: "PAID",
    },
    {
        id: 7,
        number: "1029",
        project: "TRAVEL BOOKING",
        client: "MARK ZANE",
        amount: "£500",
        date: "21.10.24",
        method: "PAYPAL",
        status: "UNPAID",
    },
    {
        id: 8,
        number: "1030",
        project: "ECOMMERCE STORE",
        client: "NINA COLE",
        amount: "£1,000",
        date: "10.09.24",
        method: "CREDIT CARD",
        status: "PAID",
    },
    {
        id: 9,
        number: "1031",
        project: "INVENTORY MANAGER",
        client: "PAUL LEE",
        amount: "£1,300",
        date: "30.08.24",
        method: "BANK TRANSFER",
        status: "PAID",
    },
    {
        id: 10,
        number: "1032",
        project: "FOOD DELIVERY APP",
        client: "SOPHIE EVANS",
        amount: "£1,100",
        date: "15.07.24",
        method: "CREDIT CARD",
        status: "PAID",
    },
    {
        id: 11,
        number: "1033",
        project: "FITNESS TRACKER",
        client: "TOM HARRIS",
        amount: "£2,000",
        date: "06.06.24",
        method: "BANK TRANSFER",
        status: "PAID",
    },
    {
        id: 12,
        number: "1034",
        project: "SOCIAL MEDIA CHAT APP",
        client: "OLIVIA BROWN",
        amount: "£850",
        date: "25.05.24",
        method: "PAYPAL",
        status: "PAID",
    },
    {
        id: 13,
        number: "1035",
        client: "DAVID CLARK",
        project: "WEATHER APP",
        amount: "£950",
        date: "13.04.24",
        method: "CREDIT CARD",
        status: "PAID",
    },
];

export const cryptoTrackerTasks = [
    { id: "1", column: "backlog", title: "Research APIs for real-time crypto data" },
    { id: "2", column: "backlog", title: "Create a mockup for the dashboard" },
    { id: "3", column: "backlog", title: "List required libraries and dependencies" },
    { id: "4", column: "todo", title: "Set up project environment" },
    { id: "5", column: "todo", title: "Build API integration for price updates" },
    { id: "6", column: "todo", title: "Design responsive layout for charts" },
    { id: "7", column: "progress", title: "Implement price alert feature" },
    { id: "8", column: "completed", title: "Integrate cryptocurrency news feed" },
    { id: "9", column: "completed", title: "Set up user authentication" },
    { id: "10", column: "completed", title: "Deploy initial version on staging" },
];

export const adminDashboardTasks = [
    { id: "1", column: "backlog", title: "Research best practices for admin dashboards" },
    { id: "2", column: "backlog", title: "Plan permissions structure for admin roles" },
    { id: "3", column: "backlog", title: "List key metrics to display on the dashboard" },
    { id: "4", column: "todo", title: "Build user management page" },
    { id: "5", column: "todo", title: "Design and implement audit logs" },
    { id: "6", column: "progress", title: "Integrate analytics for admin activities" },
    { id: "7", column: "completed", title: "Create custom reports feature" },
    { id: "8", column: "completed", title: "Add role-based access control (RBAC)" },
    { id: "9", column: "completed", title: "Set up project structure" },
    { id: "10", column: "completed", title: "Create UI mockups for the dashboard" },
    { id: "11", column: "completed", title: "Implement basic navigation between pages" },
];

export const portfolioTasks = [
    { id: "1", column: "backlog", title: "Research portfolio design trends" },
    { id: "2", column: "backlog", title: "Plan sections for the portfolio (e.g., About, Projects)" },
    { id: "3", column: "todo", title: "Set up project environment" },
    { id: "4", column: "todo", title: "Create reusable UI components" },
    { id: "5", column: "todo", title: "Build a responsive navigation bar" },
    { id: "6", column: "progress", title: "Implement dark mode toggle" },
    { id: "7", column: "progress", title: "Add animations to project cards" },
    { id: "8", column: "progress", title: "Optimize images for web performance" },
    { id: "9", column: "completed", title: "Create wireframes" },
    { id: "10", column: "completed", title: "Design color palette and typography" },
    { id: "11", column: "completed", title: "Implement contact form with email integration" },
];

export const projectTasks: { [key: string]: { id: string; column: string; title: string }[] } = {
    "1": cryptoTrackerTasks,
    "2": adminDashboardTasks,
    "3": portfolioTasks,
};  

export const jaredHubertActivity = [
    { text: "Completed initial consultation for the Crypto Tracker project.", date: "16.01.25" },
    { text: "Received payment for the Crypto Tracker development phase.", date: "14.01.25" },
    { text: "Reviewed and approved the final design for the Crypto Tracker.", date: "11.01.25" },
    { text: "Discussed project scope and next steps for Crypto Tracker.", date: "08.01.25" },
    { text: "Scheduled a follow-up meeting to assess progress on Crypto Tracker.", date: "03.01.25" },
];

export const emmaJonesActivity = [
    { text: "Finalized the initial design for the Admin Dashboard.", date: "16.01.25" },
    { text: "Approved changes to the Admin Dashboard interface.", date: "14.01.25" },
    { text: "Held a meeting to discuss the integration of new features for Admin Dashboard.", date: "11.01.25" },
    { text: "Completed the first round of testing for Admin Dashboard.", date: "08.01.25" },
    { text: "Started planning the next sprint for Admin Dashboard improvements.", date: "03.01.25" },
];

export const steveWorksActivity = [
    { text: "Provided feedback on the initial designs for the Portfolio project.", date: "16.01.25" },
    { text: "Completed the second round of testing for the Portfolio project.", date: "14.01.25" },
    { text: "Scheduled a review meeting for the Portfolio project's next phase.", date: "11.01.25" },
    { text: "Reviewed the Portfolio project presentation and provided feedback.", date: "08.01.25" },
    { text: "Confirmed the final timeline for Portfolio project delivery.", date: "03.01.25" },
];

export const activities: { [id: string]: { text: string; date: string }[] } = { 
    "0": jaredHubertActivity,
    "1": emmaJonesActivity,
    "2": steveWorksActivity,
}; 